language: python

dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - libgconf-2-4

install:
  - pip install pip --upgrade
  - pip install -e .
  - pip install -e '.[tests]'

env:
  - CYPRESS_VIDEO=false

before_script:
  - npm install -g npm@6.4.1
  - |
    echo '{"interactor": {"database": {"uri": "sqlite:///:memory:"}}}' > interactor.yml
  - photons-interactor npm run -- ci

script:
  - ./test.sh -v
  - photons-interactor npm test --silent
  - ./integrationjstest.sh
