language: python

python: 3.6

install:
  - pip install pip --upgrade
  - pip install -e .
  - pip install -e '.[tests]'

env:
  - CYPRESS_VIDEO=false

before_script:
  - npm install -g npm
  - |
    echo '{"interactor": {"database": {"uri": "sqlite:///:memory:"}}}' > interactor.yml
  - photons-interactor npm run -- ci

script:
  - ./test.sh
  - photons-interactor npm test --silent
  - ./integrationjstest.sh
